client:
#  THESE_WILL_BE_IMPORTED: "to the config file to be used as variables"
#  STORE: "sensitive data in this file"
  #######################################################################
  ZM_API: ${ML_INSTALL_CLIENT_ZM_API}
  ZM_PORTAL: ${ML_INSTALL_CLIENT_ZM_PORTAL}
  ZM_USER: ${ML_INSTALL_CLIENT_ZM_USER}
  ZM_PASS: ${ML_INSTALL_CLIENT_ZM_PASS}

  MLAPI_USER: imoz
  MLAPI_PASS: zomi

  GOTI_HOST:
  GOTI_PORTAL:
  GOTI_TOKEN:

  PUSHOVER_TOKEN: <change me>
  PUSHOVER_KEY: <change me>

  LINKURL_USER:
  LINKURL_PASS:

  MQTT_BROKER: 127.0.0.1
  MQTT_USERNAME:
  MQTT_PASSWORD:

  # The CloudFlare ZeroTrustAccess (ZTA) service token to bypass
  # the CloudFlare WAF if you use it (argo tunnels auth, etc.)
  ZM_CF_0TRUST_SECRET:
  ZM_CF_0TRUST_HEADER:
  # Copy and Paste the expiry string
  ZM_CF_0TRUST_EXPIRES:

server:
  # Store server secrets here
#  THESE_WILL_BE_IMPORTED: "to the config file to be used as variables"
#  STORE: "sensitive data in this file"
  #######################################################################
  JWT_SIGN_PHRASE: 'WIP, change me once this is implemented'
  # Plate Recognizer Cloud API key (They have a free tier!)
  # Platrec have other PAID services, I can potentially implement those as well if someone grants me access.
  PLATEREC_API_KEY:

  # WIP, I need to get someone to allow me access to their API creds to implement this. I'm cheap :)
  # Rekor also offers other services. I can potentially implement those as well.
  REKOR_KEY: